# Generated by Django 5.1.13 on 2025-11-04 01:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0055_alter_geoserverpublishchannel_expire_client_cache_after_n_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geoservergroupuser',
            unique_together={('user', 'geoserver_group')},
        ),
    ]
